### ISSUE TITLE
Cannot declare class controller, because the name is already in use

### ISSUE THREAD

**Issue by monsterlane** [kenjis/ci-phpunit-test#180] opened 2017-03-30 16:39 UTC
How can I figure out why my controllers are being loaded multiple times? We do use a modified router to append '_controller' to the filename so we can use model's without the _model suffix. Here's the code I'm using to do that which shouldn't cause any issues since it uses require_once:

```php
	protected function _set_request( $segments = array( ) ) {
		$segments = $this->_validate_request( $segments );

		if ( empty( $segments ) ) {
			$this->_set_default_controller( );
			return;
		}

		if ( $this->translate_uri_dashes === TRUE ) {
			$segments[ 0 ] = str_replace( '-', '_', $segments[ 0 ] );

			if ( isset( $segments[ 1 ] ) ) {
				$segments[ 1 ] = str_replace( '-', '_', $segments[ 1 ] );
			}
		}

		$this->set_directory( $segments[ 0 ] );
		$this->set_class( $segments[ 0 ] . '_controller' );

		if ( isset( $segments[ 1 ] ) ) {
			$this->set_method( $segments[ 1 ] );
		}
		else {
			$segments[ 1 ] = 'index';
		}

		array_unshift( $segments, NULL );
		unset( $segments[ 0 ] );

		$this->uri->rsegments = $segments;
	}

	protected function _validate_request( $segments ) {
		$c = count( $segments );

		while ($c-- > 0) {
			$test = $this->directory . ucfirst( $this->translate_uri_dashes === TRUE ? str_replace( '-', '_', $segments[ 0 ] ) : $segments[ 0 ] );

			if ( !file_exists( APPPATH . 'controllers/' . $this->directory . $test . '_controller.php' ) && is_dir( APPPATH . 'controllers/' . $this->directory . $segments[ 0 ] ) ) {
				$this->set_directory( $segments[ 0 ], TRUE );
				continue;
			}

			return $segments;
		}

		return $segments;
	}

	public function set_method( $method ) {
		parent::set_method( $method );

		if ( file_exists( APPPATH . 'controllers/' . $this->directory . $this->class . '.php' ) === true || is_file( APPPATH . 'controllers/' . $this->directory . $this->class . '.php' ) === true ) {
			if ( class_exists( 'Controller' ) === false ) {
				require_once( BASEPATH . 'core/Controller.php' );
			}

			if ( class_exists( 'MY_Controller' ) === false ) {
				require_once( APPPATH . 'core/MY_Controller.php' );
			}

			if ( class_exists( ucfirst( $this->class ) ) === false ) {
				require_once( APPPATH . 'controllers/' . $this->directory . ucfirst( $this->class ) . '.php' );
			}

			if ( class_exists( ucfirst( $this->class ) ) === true ) {
				$methods = array_map( 'strtolower', get_class_methods( ucfirst( $this->class ) ) );

				if ( in_array( strtolower( $this->method ), $methods ) === false ) {
					$this->set_directory( 'error' );

					$this->class = 'error_controller';
					$this->method = 'index';
				}
			}
		}
	}
```

I saw a few other closed issues for the same message and all seemed to point to using require vs require_once. I searched through all our code and we do not have any require statements. If I wrap all my controllers if a class_exists check phpunit will run but that's obviously not the correct way to solve the error.

Any ideas on what else I can check for to track down why this is happening? We aren't doing anything weird like making two controllers with the same name. All the config files don't define or require anything and all the helpers have function exists checks on them.

**Comment by kenjis** [comment] 2017-04-01 02:25
You mean if you remove 4 if statements `if ( class_exists( '...' ) === false )`, you get the error, right?

What is the exact error message?

**Comment by monsterlane** [comment] 2017-04-01 16:54
No it happens with that exact code. This is the error it happens with any controller:

`Fatal error: Cannot declare class Cron_controller, because the name is already in use in /Users/private/application/controllers/cron/Cron_controller.php on line 703`

Line 703 is the closing brace. If I wrap the class in class_exists === false it works so the file is being included twice somehow.

**Comment by kenjis** [comment] 2017-04-02 00:07
Please check from where is the Cron controller called.
You can probably check it, if you add `debug_print_backtrace(); exit();` in the class file.

**Comment by monsterlane** [comment] 2017-04-02 05:09
If I wrap my controllers in this:

`if ( class_exists( 'Cron_controller' ) === false ) {
}
else {
	debug_print_backtrace( );
	exit( );
}
`

I get this:

`Backtrace:
	File: /private/application/controllers/cron/Cron_controller.php
	Line: 707
	Function: debug_print_backtrace

	File: /private/application/tests/_ci_phpunit_test/CIPHPUnitTestRouter.php
	Line: 35
	Function: require_once

	File: /private/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php
	Line: 267
	Function: getRoute

	File: /private/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php
	Line: 151
	Function: requestUri

	File: /private/application/tests/_ci_phpunit_test/CIPHPUnitTestCase.php
	Line: 183
	Function: request

	File: /private/application/tests/controllers/Cron_test.php
	Line: 5
	Function: request

	File: phar:///Users/jonathan/Sites/proposify-revamp/private/application/tests/phpunit.phar/phpunit/Framework/TestCase.php
	Line: 1042
	Function: invokeArgs

	File: phar:///private/application/tests/phpunit.phar/phpunit/Framework/TestCase.php
	Line: 901
	Function: runTest

	File: phar:///private/application/tests/phpunit.phar/phpunit/Framework/TestResult.php
	Line: 697
	Function: runBare

	File: phar:///private/application/tests/phpunit.phar/phpunit/Framework/TestCase.php
	Line: 856
	Function: run

	File: phar:///private/application/tests/phpunit.phar/phpunit/Framework/TestSuite.php
	Line: 739
	Function: run

	File: phar:///private/application/tests/phpunit.phar/phpunit/Framework/TestSuite.php
	Line: 739
	Function: run

	File: phar:///private/application/tests/phpunit.phar/phpunit/TextUI/TestRunner.php
	Line: 514
	Function: run

	File: phar:///private/application/tests/phpunit.phar/phpunit/TextUI/Command.php
	Line: 207
	Function: doRun

	File: phar:///private/application/tests/phpunit.phar/phpunit/TextUI/Command.php
	Line: 136
	Function: run

	File: /private/application/tests/phpunit.phar
	Line: 468
	Function: main
`

**Comment by kenjis** [comment] 2017-04-02 11:14
This is the line to load the class file.

~~~
	File: /private/application/tests/_ci_phpunit_test/CIPHPUnitTestRouter.php
	Line: 35
	Function: require_once
~~~

And where is the first place to load it? What if you just put `debug_print_backtrace(); exit();` in the first line of the class file?

One more thing, you have a modified router, so you may have to modify `CIPHPUnitTestRouter.php`.
It is used when you use `$this->request()`.

**Comment by monsterlane** [comment] 2017-04-02 20:28
If I put at as the first lines in my controller I get this:

```Fatal error: Cannot declare class Cron_controller, because the name is already in use in /Users/private/application/controllers/cron/Cron_controller.php on line 706

Fatal error: Uncaught LogicException: CodeIgniter instance is not instantiated yet. You can't use `$this->output` at the moment. Please fix your test code. in /private/application/tests/_ci_phpunit_test/CIPHPUnitTestNullCodeIgniter.php:18
Stack trace:
#0 /private/application/tests/_ci_phpunit_test/replacing/core/Common.php(269): CIPHPUnitTestNullCodeIgniter->__get('output')
#1 /private/system/core/Common.php(607): set_status_header(500)
#2 /private/system/core/Common.php(689): _error_handler(64, 'Cannot declare ...', '/Users/...', 706)
#3 [internal function]: _shutdown_handler()
#4 {main}
  thrown in /private/application/tests/_ci_phpunit_test/CIPHPUnitTestNullCodeIgniter.php on line 18```

If I put a class_exists check around the require_once in CIPHPUnitTestRouter.php it doesn't throw an error. I put a die(var_dump('go')) statement in CI's redirect function to see if I was looping the request somehow and it never hit the die.

**Comment by stebogit** [comment] 2017-12-07 23:55
Just to add some input that might help fund the bug; I get the same error if I run this:
```php
private function newControllerWithParams($classname, $params)
{
    reset_instance();
    $controller = new $classname($params);
    $this->CI =& get_instance();
    return $controller;
}
...

$controller = $this->newControllerWithParams('MyController', $someParameter);
$controller->method($arg1, $arg2);
```
before another test (for the same controller) where is used this:
```php
$this->request('GET', 'mycontroller/anothermethod/arg');
```

However the error does not occur if I run the tests individually or together in the opposite order.

**Comment by daniboyBr** [comment] 2019-08-05 18:45
Fatal error: Cannot declare class Home, because the name is already in use in

I believe the error I received after running the tests was caused by my controllers having subfolders an the same name. Does anyone have any idea how to fix the error?

For example
codeigniter/
├── application/
 |    └── controllers/
 |          └── Situation/
 |                ├── Home.php
 |          └── Maps/
 |               ├── Home.php
│   └── tests/
└── vendor/


`<?php

class Situation_test extends TestCase{

     public function test_AccessSituationHome()
    {
        $output = $this->request('GET','Situation/Home/index'); //index is the method returning the view
        $this->assertContains('<h1>Siuation Home</h1>' , $output);
    }
}
`

`
class Maps_test extends TestCase{

     public function test_AccessMapsHome()
    {
        $output = $this->request('GET','Maps/Home/index'); //index is the method returning the view
        $this->assertContains('<h1>Maps Home</h1>', $output );
    }
}

`

**Comment by bvrignaud** [comment] 2019-08-06 08:14
I had this on the top of my test :
```php
/**
 * @runInSeparateProcess
 * @preserveGlobalState disabled
 */
 public function test_index()
 {
```

**Comment by kenjis** [comment] 2019-08-06 12:20
Yes. See <https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#controller-with-name-collision>.

**Comment by daniboyBr** [comment] 2019-08-06 13:10
I had already tried with this annotation and it got me the following phpunit error (phpunit --verbose) and it shows nothing else.

Note: I am performing these tests on my work project so I can't be putting the real code here. I am showing how I did with these examples. And that's exactly how I did it

PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.32-1~dotdeb+8.1 with Xdebug 2.5.5
Configuration: /var/www/supra_cgpert/application/tests/phpunit.xml

EE.                                                          3 / 3 (100%)

Time: 26.18 seconds, Memory: 14.00MB

There were 2 errors:

1) Situation_test::test_AccessSituationHome
2) Maps_test::test_AccessMapsHome

ERRORS!
Tests: 3, Assertions: 1, Errors: 2.

**Comment by daniboyBr** [comment] 2019-08-06 15:20
Thank you very much,

The annotation is working as it should, php was with configuration error below:

Unable to load dynamic library '/usr/lib/php/20151012/php_gd2.dll'

Tests with the @runInSeparateProcess annotation were going through, but phpunit caught the Unable to load dynamic library error. I fixed the error and all tests passed without problems.


And sorry for the inconvenience because I'm still learning

Your help was very helpful

**Comment by kenjis** [comment] 2019-08-10 09:46
@daniboyBr Good to hear.

This issue is too old. I close it.

**Closed by kenjis** 2019-08-10 09:46 UTC
Labels: help wanted
