### ISSUE TITLE
Testing Result Controller 

### ISSUE THREAD

**Issue by lighter** [kenjis/ci-phpunit-test#125] opened 2016-06-22 02:43 UTC
Hi, I had a problem it's like #46 .

I use https://github.com/chriskacerguis/codeigniter-restserver/releases (v.2.7.7). And I try to modify the `REST_Controller`

```
{
    call_user_func_array([$this, $controller_method], $arguments);
}
catch (CIPHPUnitTestExitException $ex) { 
    // This block is for ci-phpunit-test 
    throw $ex; 
}
catch (Exception $ex) {
```

My test is simple

```
class Example_test extends TestCase
{
    public function test_When_get_users_Then_returns_all_user_data()
    {
        try
        {
            # var_dump('a'); // show on the terminal
            $output = $this->request('GET', 'api/example/users');
            # var_dump('b'); // not show on the terminal
        }
        catch (CIPHPUnitTestExitException $e)
        {
            $output = ob_get_clean();
        }

        $data = json_decode($output, true);
        $this->assertCount(3, $data);
        $this->assertResponseCode(200);
    }
}
```

I try to run this test, I got the request output on the terminal.

```
$ php phpunit controller/api/Example_test.php

[{"id":1,"name":"John","email":"john@example.com","fact":"Loves coding:},{...},...]
```

And I found the problem is `libraries/Rest_Controller.php` 

```
public function response($data = NULL, $http_code = NULL, $continue = FALSE)
{

        if ($continue === FALSE)
        {
            // Display the data and exit execution
            $this->output->_display();
            exit; # -----> Interrupt test
        }
}
```

On Linux run the is work(PHP version is 5.6). On Windows not work(PHP version is 5.4).

**Comment by kenjis** [comment] 2016-06-22 09:01
See https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#codeigniter-rest-server

You have to enable Monkey Patching.

**Comment by lighter** [comment] 2016-06-22 09:29
I had enabled Monkey Patching on the `applicaiton/tets/Bootstrap.php`

**Comment by kenjis** [comment] 2016-06-22 12:26
@lighter 
> On Linux run the is work(PHP version is 5.6). On Windows not work(PHP version is 5.4).

What do you mean?
On Linux your test works fine, but on Windows it does not work?

**Comment by lighter** [comment] 2016-06-22 14:13
I have two environments, one is on the Linux(I use docker to build, PHP version is 5.6), the other one is on the Windows, I use the XAMPP(PHP version is 5.4). Because the code is same.

**Comment by kenjis** [comment] 2016-06-22 21:13
If you use the exact same code, it seems there is a bug which only occurs on Windows.
To look into it, I need to install XAMPP on Windows. It takes some time.
If you find any clue, let me know.

**Comment by kenjis** [comment] 2016-07-23 11:18
@lighter 
On Windows, I confirmed the monkey patching does not work.

**Comment by lighter** [comment] 2016-07-23 11:23
You mean the monkey patching can't run on the windows, right?

**Comment by kenjis** [comment] 2016-07-23 11:37
Yes and no. It is a bug. I will fix it.

**Comment by kenjis** [comment] 2016-07-23 11:43
@lighter 
I pushed the fix to `master` branch: https://github.com/kenjis/ci-phpunit-test/commit/554f03c3fe5017c02ed9952593771564b2b657b3
It will be included in the next release version.

**Comment by lighter** [comment] 2016-08-01 06:41
Thank, it works for me. And I have another question, it's about MonkeyPatchManager, on the `test/Bootstrap.php`

This is my project folder structure

```
c:\xampp\htdocs\travels
   |--- _ci_phpunit_test
   |--- ci_common
      |--- common // overwrite some of CI class, ex DB_driver
      |--- system // all the project will use the system
   |--- ticket
      |--- application // one of my project
      |--- test
```

When I run my library test, I will get the `DB_drvier.php` error message

```
Unknown column 'QQQQ' in 'field list'
<MY_SQL_QUERY>
```

This is echo by `$this->display_error()`, on the `DB_dirver.php` I think it should not show it on the terminal, right?

And I try to see the detail, I founded the MonkeyPatchManager will write temp cache. This is my include paths.

```
...
MonkeyPatchManager::init([
    ...
    include_paths => [
        // c:\xampp\htdocs\travels\ticket\application
        APPPATH,
        
        // c:\xampp\htdocs\travels\ci_common\common
        APROJECTPATH,

       // c:\xampp\htdocs\travels\ci_common\system
        BASEPATH,
    ],
    ...
]);
...
```

I put the system to the `ci_common\system` folder, and I put overwrite code on the `ci_common\common`.

And I founded the `_ci_phpunit_test\patcher\Cache.php` I had to modify the `getSrcCacheFilePath()` , if I use original, I will get a wrong path. Does it right? Because I'm not sure  the `tmp\cache\src` path use for what. 

And I got the result

```
_ci_phpunit_test
|--- temp
   |--- cache
      |--- src
      |--- application
      |--- ci_common
         |--- system
         |--- common
```

And I check the `tmp\cache\autoload.php` I got the result is

```
a:4:{s:17:"CIPHPUnitTestCase";s:63:"c:\xampp\travels\_ci_phpunit_test\CIPHPUnitTestCase.php";
...CIPHPUnitTestSuperGlobal.php";...CIPHPUnitTestNullCodeIgniter.php";...CIPHPUnitTestExitException.php";}
```

I think I should modify the `autolad.php` right?

I think the `autoload.php` miss something, right?

**Comment by kenjis** [comment] 2016-08-01 22:54
The files in `tmp\cache\src` is source files which are modified by Monkey patching.
Monkey patching run them when you run phpunit.

Maybe you have to add `root_dir` in `MonkeyPatchManager::init()`. The following is the hidden default value:

```
	// Project root directory
	'root_dir' => APPPATH . '../',
```

`tmp\cache\autoload.php` is a cache file which is created by ci-phpunit-test's autoloader.
It contains a serialized array. The key is classname, the value is the file path for the class.

**Comment by lighter** [comment] 2016-08-03 10:06
Thanks your help. But I have one more question, In my model's code, like this

```
class Test_model extends CI_Model {
...

    public function test_query() {
        try
        {
            // This is a wrong sql
            $sql = "SELECT XXXXX"; 
            
            // The query result is failed. I Think this line should throw a exit exception.
            $query = $this->db->query($sql); 

            if (false !== $query)
            {
                return $query->result_array();
            }          
            else
            {
                throw new Exception('sql error', 310);
            }  
        }
        catch (Exception $e)
        {
            // set error message log
        }

        return false;
    }

...
}
```

And this is my model test code

```
...
    public function test_model_query()
    {
        try 
        {
            $result = $this->ojb->test_query();
        }
        catch (CIPHPUnitTestExitException $e)
        {
            // It should run there?
            eval(\Psy\sh());
        }
    }
...
```

I should get a `CIPHPUnitTestExitEception` right? Because my SQL is wrong. It should call the `DB_driver -> display_error() -> exit__(8)`. But I got the `$result` is false and I don't have any `CIPHPUnitTestExitException`.

**Comment by lighter** [comment] 2016-08-03 11:44
I founded, the problem is model's `try cache`.

**Comment by kenjis** [comment] 2016-08-03 11:48
@lighter I close this issue. Because its title no longer shows its contains.
If you have any question, please create another issue.

**Closed by kenjis** 2016-08-03 11:48 UTC
Labels: bug, help wanted

**Comment by chriskacerguis** [comment] 2017-01-01 01:31
@kenjis hey, thanks for writing this test suite for chriskacerguis/codeigniter-restserver I have updated the code, and the "exit" is no longer used (I just removed it).  It will be in the next (2.8.1) release.

/cc @lighter
